// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var Driver, customPhantom, phantomjs_exe, selenium;

  selenium = require('selenium-webdriver');

  phantomjs_exe = require('phantomjs-prebuilt').path;

  customPhantom = selenium.Capabilities.phantomjs();

  customPhantom.set("phantomjs.binary.path", phantomjs_exe);

  Driver = function() {
    this.use = new selenium.Builder().withCapabilities(customPhantom).build();
    this.use.getWindowHandle();
    return true;
  };

  Driver.prototype.close = function() {
    return this.use.quit();
  };

  module.exports = Driver;

}).call(this);
