// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive({
      matcher: 'selenium_instance',
      it: 'closes the driver instance',
      i: [],
      e: 'function'
    });
  };

}).call(this);
