// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var spec;

  spec = require('ddry/modular')();

  spec.apply({
    title: 'Selenium PhantomJS testing',
    spec: 'spec',
    matchers: 'ddry-selenium-matchers',
    moduleTitles: {
      phantomjs: 'Selenium PhantomJS testing'
    },
    outside: {
      phantomjs: 'index'
    },
    use: ['phantomjs']
  });

}).call(this);
